parameters:
- name: type
  type: string
- name: stageName
  type: string
  default: Publishes nuget to nightly feed
- name: environment
  type: string
- name: libraryArtifactName
  type: string
  default: $(Build.Repository.Name)-$(Build.BuildNumber)
- name: feedCredentials
  type: string

stages:
  - stage: Publish_${{ parameters.type }}
    displayName: Publishes nugets to feed
    dependsOn:
      - Build
      - Test
    condition: succeeded()
    jobs:
      - deployment: KritikosIO
        displayName: ${{ parameters.stageName }}
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
              - template: ../../steps/dotnet/nuget-push.yml
                parameters:
                  nugetDirectory: $(Pipeline.Workspace)/{{ parameters.libraryArtifactName }}
                  feedCredentials: ${{ parameters.feedCredentials }}
