parameters:
- name: stageName
  type: string
  default: Publishes nuget to nightly feed
- name: configuration
  type: string
  default: $(BuildConfiguration)
- name: libraryArtifactName
  type: string
  default: $(Build.Repository.Name)-$(Build.BuildNumber)
- name: feedCredentials
  type: string

stages:
  - stage: PublishCI
    displayName: Publishes nugets to nightly feed
    dependsOn:
      - Build
      - Test
    condition: succeeded()
    jobs:
      - deployment: KritikosIO
        displayName: ${{ parameters.stageName }}
        environment: Kritikos-io
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: ${{ parameters.libraryArtifactName }}
              - template: ../../steps/dotnet/nuget-push.yml
                parameters:
                  nugetDirectory: $(Pipeline.Workspace)/{{ parameters.libraryArtifactName }}
                  feedCredentials: ${{ parameters.feedCredentials }}
                  configuration: ${{ parameters.configuration }}
